Update Config Connector lab
- Update Workload Identity -> Workload Identity Federation for GKE and add
some notes
- Update Pub/Sub topic allowed storage regions to avoid hitting an org
  policy constraint [1]
- Update message publish command to use a regional endpoint, otherwise
  it'll fail [2]

[1]
"Update call failed: error applying desired state: summary: Error creating Topic: googleapi: Error 400: The org policy `constraints/pubsub.enforceInTransitRegions` requires enforcement in transit but the org policy `constraints/gcp.resourceLocations` allows all regions."
[2]
ERROR: (gcloud.pubsub.topics.publish) FAILED_PRECONDITION: The topic's message storage policy requires enforcement in transit, but the Publish request was received by a Pub/Sub server in a non-allowed region. Please either publish via a regional Pub/Sub endpoint corresponding to an allowed region, or update the topic's message storage policy.